eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 9089
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true

